name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
      - run: yarn build
      - uses: codecov/codecov-action@v1