name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - uses: codecov/codecov-action@v2
