name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: Borales/actions-yarn@v2.3.0
        with:
          node-version: 12.x
      - run: yarn install -f
      - run: yarn test
      - run: yarn build
      - uses: codecov/codecov-action@v1
